[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "peets"
version = "0.0.1"
dependencies = [
    "requests",
    "lxml",
    "tmdbsimple = 2.9.1",
    "reflink = 0.2.1",
]