from enum import Enum, auto

class MediaGenres(Enum):
    """ Genres from tinyMediaManager

    https://gitlab.com/tinyMediaManager/tinyMediaManager/-/blob/devel/src/main/java/org/tinymediamanager/core/entities/MediaGenres.java
    """
    ACTION = auto()
    ADVENTURE = auto()
    ANIMATION = auto()
    ANIME = auto()
    ANIMAL = auto()
    BIOGRAPHY = auto()
    COMEDY = auto()
    CRIME = auto()
    DISASTER = auto()
    DOCUMENTARY = auto()
    DRAMA = auto()
    EASTERN = auto()
    EROTIC = auto()
    FAMILY = auto()
    FAN_FILM = auto()
    FANTASY = auto()
    FILM_NOIR = auto()
    FOREIGN = auto()
    GAME_SHOW = auto()
    HISTORY = auto()
    HOLIDAY = auto()
    HORROR = auto()
    INDIE = auto()
    MINI_SERIES = auto()
    MUSIC = auto()
    MUSICAL = auto()
    MYSTERY = auto()
    NEO_NOIR = auto()
    NEWS = auto()
    REALITY_TV = auto()
    ROAD_MOVIE = auto()
    ROMANCE = auto()
    SCIENCE_FICTION = auto()
    SERIES = auto()
    SHORT = auto()
    SILENT_MOVIE = auto()
    SOAP = auto()
    SPORT = auto()
    SPORTING_EVENT = auto()
    SPORTS_FILM = auto()
    SUSPENSE = auto()
    TALK_SHOW = auto()
    TV_MOVIE = auto()
    THRILLER = auto()
    WAR = auto()
    WESTERN = auto()
